### ISSUE TITLE
blur-edges partially works

### ISSUE THREAD

**Issue by wmfaria** [occivink/mpv-scripts#10]
First I have to say that your scripts are awesome! Thanks for sharing!
Probably I am too newbie to the MPV world, but I gotta ask you this..

When using your script I get the blur effect working on the left half of the screen (above and below the video)  while the right half of the screen shows a green fill instead of the blur effect.. My screen gets divided right in the middle, the left part working, and the right part filled with green... Could you help my find out whats happening?

Thank you very much!

**Comment by occivink** [comment]
Interesting, I remember this happening a while ago when the size of the blur was set incorrectly.

Could you please add the line `print(filter)` [there](https://github.com/occivink/mpv-scripts/blob/master/scripts/blur-edges.lua#L78), and copy/paste what appears on the terminal? (I really ought to add debug prints by default).

And if possible, please upload a short extract of the video.

**Comment by wmfaria** [comment]
Hi! Well, I managed to acquire these information, hope it helps:

I printed the filter as you asked me to... the output is this:
[blur] [vid1] split=3 [a] [v] [b];[a] crop=1280:92:0:0,boxblur=lr=10:lp=10:cr=10
:cp=10 [a_fin];[b] crop=1280:92:0:444,boxblur=lr=10:lp=10:cr=10:cp=10 [b_fin];[a
_fin] [v] [b_fin] vstack=3 [vo]

I got a screenshot of the output video:
![sample](https://user-images.githubusercontent.com/36427933/36155979-f8c30cbc-10bc-11e8-903e-67fb33d5cdf5.jpg)

There is a green color fill on half of the screen, but the blur works behind this fill...

Another thing I see when I turn on the blur is that my OSD progress bar gets resized to a bigger size.. The image above shows this.. The OSD is a lot bigger with the blur on..

**Comment by occivink** [comment]
Mmh I can't reproduce this, I even went ahead and got the same file but it works fine for me, so let's try to diagnose it. 

* Can you post the output of `mpv --version`? If it's not the latest version, try updating.
* On which platform are you?
* Are you using hardware decoding?
* Can you try playing this file without any configuration, just the script? Try `mpv --no-config --script /path/to/blur-edges.lua movie.mkv`

**Comment by wmfaria** [comment]
Bull's eye! You got it..

I checked the items above and located the mpv.conf file, the video settings was set like so:
## VIDEO ##
gpu-api=d3d11
hwdec=auto-copy
deinterlace=auto
interpolation
video-sync=display-resample
framedrop=vo
deband
deband-grain=80
dither-depth=8
scaler-resizes-only
sigmoid-upscaling
scale=spline36
scale-antiring=1.0
cscale=ewa_lanczossoft
cscale-antiring=1.0
dscale=mitchell
dscale-antiring=1.0
tscale=mitchell
tscale-antiring=1.0

After deleting this whole block, the blur effect worked like a charm!

I do not know whats the best video settings for my pc, but leaving it blank worked nicely!
My system info:
Windows 7 x64
8GB Ram
Intel(R) Core(TM) i3-3240 CPU @ 3.40GHz
Video: ATI Radeon 7770

Thank you so much for you attention and availability!
