### ISSUE TITLE
Key binding names in `start_crop()` and `cancel_crop()` should be the same

### ISSUE THREAD

**Issue by gitterliu** [occivink/mpv-scripts#12]
Key binding names in `start_crop()` should be `"crop-"..key`.

https://github.com/occivink/mpv-scripts/blob/1ecd29ec9a3796639fb14c467f0fb78e49a9a9c0/scripts/crop.lua#L321

https://github.com/occivink/mpv-scripts/blob/1ecd29ec9a3796639fb14c467f0fb78e49a9a9c0/scripts/crop.lua#L324

https://github.com/occivink/mpv-scripts/blob/1ecd29ec9a3796639fb14c467f0fb78e49a9a9c0/scripts/crop.lua#L377

https://github.com/occivink/mpv-scripts/blob/1ecd29ec9a3796639fb14c467f0fb78e49a9a9c0/scripts/crop.lua#L380

**Comment by occivink** [comment]
Thanks!
