### ISSUE TITLE
encode_slice - Possible to 'copy' the container format?

### ISSUE THREAD

**Issue by joeynotjoe** [occivink/mpv-scripts#17]
Hello!

I am wondering how, to get my _slice profile to not use a set container. I had it set to mkv, but I ran into an mp4 source that had incompatible subtitle attachments. It would be great if there was a way to copy the extension/container when copying all streams.

**Comment by occivink** [comment]
I think a reasonable way to do that would be to merge the variables `output_format` and `container`, and expose a variable `$x` to represent the container of the input file, you could just do 
```
output_format=$f_$n.$x
```
and forcing a container would be done with 
```
output_format=$f_$n.webm
```
