### ISSUE TITLE
encode.lua $only_active_tracks does not seem to work

### ISSUE THREAD

**Issue by paradox460** [occivink/mpv-scripts#2]
When you set `only_active_tracks` to `true`, the resulting ffmpeg command has a `-map` value without parameters, causing it to fail.

**Comment by occivink** [comment]
Thanks, there was some non-sensical handling for this particular variable.

**Comment by paradox460** [comment]
No worries, i managed to make due by aliasing ffmpeg to `true`, and manually copying the command output down and running it later. Your script collection is the best i've come across so far

**Comment by occivink** [comment]
Thank you, I appreciate the kind words.
