### ISSUE TITLE
[blur edges] zoom

### ISSUE THREAD

**Issue by ubone** [occivink/mpv-scripts#24]
currently the background is tiled and duplicated, can filters zoom it instead?
meaning fit bg video's width to screen and keep its aspect ratio

**Comment by occivink** [comment]
I don't think I get it, do you have an example or a mockup of what it would look like?

**Comment by ubone** [comment]
sure i'll try to explain, at the moment we have the real video in the middle and one blurred copy on the left and one on the right, instead you'd have the real video in the middle and only one video in the back which is also centered but enlarged until it's width touches the screen edge, but keeping it's aspect ratio

**Comment by occivink** [comment]
That makes some sense, is this how other applications usually do it? Alternatively if the goal is to just fill the bars, we could simply stretch the blurred parts, I don't think we care much for the aspect ratio there.

**Comment by ubone** [comment]
> other applications

idk, I've seen news do it like this.
Stretch would look bad imo, the aspect ratio gives a good sense for the video.

**Comment by occivink** [comment]
This was a pain to get working, but you're right that it looks better
