### ISSUE TITLE
youtube-dl and audio

### ISSUE THREAD

**Issue by AeliusSaionji** [occivink/mpv-scripts#25]
Hello!

When playing a video from youtube with separate audio and video streams, encode.lua only operates on the video stream and omits the audio. Would it be possible to include external audio streams in the conversion?

Thanks!

**Comment by occivink** [comment]
Is this a video that was downloaded as a file using `youtube-dl` and then opened with mpv, or is it being streamed from youtube directly? In either case, could you provide an example of how to reproduce this?

**Comment by AeliusSaionji** [comment]
Simply stream a YouTube video with `mpv http://YouTube....`

I assume the issue would probably happen with any video where mpv loaded audio/subs from an external file.

**Comment by occivink** [comment]
You're right, for such videos the audio track appears as external and has its own url. It looks all the necessary information is available so I think it's just a matter of passing that properly to ffmpeg, I'll take a look at it this weekend

**Comment by AeliusSaionji** [comment]
Thanks! But I think this may have broken using encode and crop at the same time?

**Comment by occivink** [comment]
Right, this is what I get for refactoring without testing much.
