### ISSUE TITLE
Crop filter doesn't work with certain resolutions

### ISSUE THREAD

**Issue by AeliusSaionji** [occivink/mpv-scripts#27]
For certain resolutions (3000x2000 is one example) I get this error when trying to use crop:
```
[ffmpeg] Impossible to convert between the formats supported by the filter 'mpv_src_default_in' and the filter 'auto_scaler_0'
[lavfi] failed to configure the filter graph
Disabling filter crop.00 because it has failed.
```

**Comment by AeliusSaionji** [comment]
Update: the converted video is still cropped, I just don't get to see the crop preview/filter while editing..

**Comment by occivink** [comment]
Is this an error in crop.lua or encode.lua? I don't quite get it

**Comment by AeliusSaionji** [comment]
It's in crop.lua. The error message is what mpv spits out when I use it.

However, the crop did work for the output video when I used encode.lua.

**Comment by occivink** [comment]
Ok, gotcha. 3000 x 2000 is the input format or after the crop? In any case if you've got a log that would be helpful

**Comment by AeliusSaionji** [comment]
3000 x 2000 is the input format. How would I get a log?

**Comment by occivink** [comment]
Use `--log-file=output.txt` and reproduce the error

**Comment by AeliusSaionji** [comment]
[output.txt](https://github.com/occivink/mpv-scripts/files/3277134/output.txt)

**Comment by occivink** [comment]
I can't see anything of interest in there. Can you try

`mpv --no-config --vf=crop:y=136:x=65:h=769:w=2560 your_big_file.mkv` ?

If that does not work, then something is up on mpv's side

**Comment by AeliusSaionji** [comment]
That works fine

**Comment by occivink** [comment]
And without the `--no-config`?

**Comment by AeliusSaionji** [comment]
It fails with my config.

config:
```
autofit-larger=80%x80%
no-border
ontop
screenshot-format=png
screenshot-template="%f [%P]"
hwdec=auto

[protocol.http]
force-window=immediate
[protocol.https]
force-window=immediate
```

**Comment by AeliusSaionji** [comment]
The problem is with hardware decoding 🤕

**Comment by occivink** [comment]
Ah right. The doc mentions this 
```
Most video filters will not work with hardware decoding as they are primarily implemented on the CPU. Some exceptions are vdpaupp, vdpaurb and vavpp. See VIDEO FILTERS for more details.

The ...-copy modes (e.g. dxva2-copy) allow you to use hardware decoding with any VO, backend or filter. Because these copy the decoded video back to system RAM, they're likely less efficient than the direct modes (like e.g. dxva2), and probably not more efficient than software decoding except for some codecs (e.g. HEVC).
```
so try `hwdec=auto-copy` ?

**Comment by AeliusSaionji** [comment]
Yeah that works, but uses 7x more cpu :/ ah well. Thanks for helping solve this!
