### ISSUE TITLE
encode_webm.conf ignores audio and subtitle tracks.

### ISSUE THREAD

**Issue by Naomi010Sentzke** [occivink/mpv-scripts#29]
Whether , I set 'only_active_tracks' as yes or no, it will only encode the video track. I want it to encode the subs too. I use Zeranoe's latest ffmpeg build.

**Comment by occivink** [comment]
Hello,
`encode_webm.conf` passes `-an -sn` as arguments to ffmpeg (see `codec` option) which respectively disable audio and subtites. You can simply remove them, and maybe add `-a copy` to avoid re-encoding the audio.

**Comment by Naomi010Sentzke** [comment]
Thanks

**Comment by slrslr** [comment]
on Linux, this command fixed the issue:
sed -i "s|-an -sn||g" ~/.config/mpv/scripts/encode.lua

**Comment by VimWei** [comment]
> -a copy

This argument can't working.
