### ISSUE TITLE
Avoid NTFS invalid characters

### ISSUE THREAD

**Issue by AeliusSaionji** [occivink/mpv-scripts#37]
Hey, sorry to bug you about Windows specific issues again, but this one has been a thorn in my side for a while now.

Youtube urls can come in two flavors:
`https://www.youtube.com/watch?v=XXXXX`
`yout.ube/XXXXX`

The first one will cause any encodings to fail on Windows because the filename contains a question mark. I would really appreciate it if we could sanitize output filenames, so I could cut out segments of streams without having to modify the url (or more likely just download the video to make sure it works).

Thanks!

**Comment by occivink** [comment]
Yeah makes sense. I'm not sure why I didn't cover all characters in that [commit](2b635f299ea3f99e1704d1f30c27d0665b0eff82)

**Comment by AeliusSaionji** [comment]
ah nice!
Probably not all of these need to be handled, but the basic list of characters that don't work is `/ ? < > \ : * | "`

**Comment by occivink** [comment]
Should be fixed in 8e282861c3871d9437a1b331fc9be57052a2908d
