### ISSUE TITLE
NUMENTER

### ISSUE THREAD

**Issue by Max-Enrik** [occivink/mpv-scripts#48]
I'd like to change `Enter` to `NumEnter` how can I do that?

**Comment by occivink** [comment]
Which script are you talking about?

**Comment by Max-Enrik** [comment]
Sorry I didn't mentioned.
I am talking about 'seek-to.lua'.

**Comment by occivink** [comment]
Alright, you need to modify this line
https://github.com/occivink/mpv-scripts/blob/master/scripts/seek-to.lua#L119
and rename `ENTER` to `KP_ENTER`

**Comment by Max-Enrik** [comment]
Thank you a lot, I used try to edit that line before the posted the question, didn't find any key code/name in google.
Where can I get that .lua keys code/name?

**Comment by occivink** [comment]
You can use `mpv --force-window --idle --input-test`. There's also this list https://github.com/mpv-player/mpv/blob/dcec6d9556c6cfca11b865442174479096f55111/input/keycodes.c

**Comment by Max-Enrik** [comment]
Thank you a ton.
