### ISSUE TITLE
About crop

### ISSUE THREAD

**Issue by kesdoputr** [occivink/mpv-scripts#5]
If is is possible to setting same hotkey to crop/undo crop?
I know the script easycrop can do this
https://github.com/aidanholm/mpv-easycrop
But i like your script that can show the position and size when cropping.

Anyway thank you for watching,if it is not possible to use the same hotkey
i will set different to use.

**Comment by occivink** [comment]
I just added a command, "toggle-crop". You should be able to bind it like that:
`c script-binding crop/toggle-crop`
It's not perfect with complex filter chains, but it should work most of the time, and hopefully with your usecase.

**Comment by kesdoputr** [comment]
It's work fine,thanks for reply so quickly.
