### ISSUE TITLE
Crop.lua videos (zoomed in) keep resetting.

### ISSUE THREAD

**Issue by pafke2** [occivink/mpv-scripts#51]
Hello, it's not really an issure, more like a small bug - i have 'loop-file=inf' in my mpv config, and  if I crop a part of a videofile and the file ends, then it plays again with the cropped part (zoomed in) still showing. But if I skip forward the videofile and the video ends, it plays again - but only this time it will completely reset and the cropped part dissapear (zoomed out).

**Comment by occivink** [comment]
That certainly looks like an mpv bug. The crop script only sets a filter, it doesn't do anything when switching file or skipping within one. If you can provide more info, I'd recommend reporting this on the mpv repository directly.

For the record, I can reproduce and the following appears in the log
```
[ffmpeg] filter: Invalid too big or non positive size for width '490' or height '372'
[ffmpeg] filter: Failed to configure input pad on filter
[lavfi] failed to configure the filter graph
Disabling filter crop.01 because it has failed.
```
