### ISSUE TITLE
encode.lua

### ISSUE THREAD

**Issue by rcspam** [occivink/mpv-scripts#6]
i have to replace
```
mp.add_key_binding(nil, "set-timestamp", set_timestamp)
mp.add_key_binding(nil, "clear-timestamp", clear_timestamp)
```
by
```
mp.add_key_binding(nil, "set_timestamp", set_timestamp)
mp.add_key_binding(nil, "clear_timestamp", clear_timestamp)
```
to do the script working

When use with crop, doesn't work with vdpau !

Cheers

**Comment by occivink** [comment]
You're right, the README was using a different syntax for the "encode" command.

>When use with crop, doesn't work with vdpau !

Unfortunately, most video filters do not work with hardware decoding. `vdpau-copy` might work, but the mpv manual mentions that it may be less efficient than `vdpau`. Note that it also mentions that hardware decoding is in general not recommended if your cpu is powerful enough to do software decoding.
